#==============================================================#
# 0430 pg_backend
#==============================================================#
pg_backend:
  name: pg_backend
  desc: PostgreSQL backend client count group by wait event type since 10
  query: SELECT backend_type AS "type", count(*) AS count FROM pg_stat_activity GROUP BY backend_type;
  ttl: 10
  min_version: 100000
  tags: [ cluster ]
  metrics:
    - type:  { usage: LABEL ,description: Database backend process type }
    - count: { usage: GAUGE ,description: Database backend process count by backend_type }


