#==============================================================#
# 0440 pg_xact
#==============================================================#
pg_xact:
  name: pg_xact
  desc: PostgreSQL transaction identifier metrics
  query: |
    WITH snap(v) AS (SELECT txid_current_snapshot()),
         xset(v) AS (SELECT txid_snapshot_xip(v) FROM snap),
         xnum(v) AS (SELECT count(*) FROM xset),
         xmin(v) AS (SELECT txid_snapshot_xmin(v) FROM snap),
         xmax(v) AS (SELECT txid_snapshot_xmax(v) FROM snap)
    SELECT xmin.v AS xmin, xmax.v AS xmax, xnum.v AS xnum
    FROM xmin, xmax, xnum;
  ttl: 10
  min_version: 90100
  tags: [ cluster ]
  metrics:
    - xmin: { usage: COUNTER ,description: Earliest txid that is still active }
    - xmax: { usage: COUNTER ,description: First as-yet-unassigned txid }
    - xnum: { usage: GAUGE   ,description: Current active transaction count }
