#==============================================================#
# 0460 pg_query
#==============================================================#
pg_query_94:
  name: pg_query
  desc: PostgreSQL query statement metrics, require pg_stat_statements installed, 9.4 - 12
  query: |-
    SELECT datname, queryid AS query, sum(calls) AS calls, sum(rows) AS rows, sum(total_time) AS exec_time, sum(blk_read_time) + sum(blk_write_time) AS io_time,
      sum(shared_blks_hit) AS sblk_hit, sum(shared_blks_read) AS sblk_read, sum(shared_blks_dirtied) AS sblk_dirtied, sum(shared_blks_written) AS sblk_written
    FROM pg_stat_statements(false) s JOIN pg_database d ON s.dbid = d.oid WHERE userid != 10 AND calls > 4 GROUP BY 1, 2 ORDER BY 3 DESC LIMIT 128;

  ttl: 10
  timeout: 2
  min_version: 90400
  max_version: 130000
  tags: [ cluster, "extension:pg_stat_statements" ]
  metrics:
    - datname:      { usage: LABEL   ,description: Name of database }
    - query:        { usage: LABEL   ,description: QueryID generated from internal hash code, computed from the statement's parse tree }
    - calls:        { usage: COUNTER ,description: Number of times the statement was executed }
    - rows:         { usage: COUNTER ,description: Total number of rows retrieved or affected by the statement }
    - exec_time:    { usage: COUNTER ,scale: 1e-3 ,description: Total time spent executing the statement, in seconds }
    - io_time:      { usage: COUNTER ,scale: 1e-3 ,description: Total time the statement spent reading and writing blocks, in seconds }
    - sblk_hit:     { usage: COUNTER ,description: Total number of shared block cache hits by the statement }
    - sblk_read:    { usage: COUNTER ,description: Total number of shared blocks read by the statement }
    - sblk_dirtied: { usage: COUNTER ,description: Total number of shared blocks dirtied by the statement }
    - sblk_written: { usage: COUNTER ,description: Total number of shared blocks written by the statement }

pg_query_91:
  name: pg_query
  desc: PostgreSQL query statement metrics, require pg_stat_statements installed, 9.1 - 9.3 (no queryid)
  query: |-
    SELECT datname, md5(query) AS query, sum(calls) AS calls, sum(rows) AS rows, sum(total_time) AS exec_time, 0::FLOAT AS io_time,
      sum(shared_blks_hit) AS sblk_hit, sum(shared_blks_read) AS sblk_read, 0::BIGINT AS sblk_dirtied, sum(shared_blks_written) AS sblk_written
    FROM pg_stat_statements s JOIN pg_database d ON s.dbid = d.oid WHERE userid != 10 AND calls > 4 GROUP BY 1, 2 ORDER BY 3 DESC LIMIT 128;

  ttl: 10
  timeout: 2
  min_version: 90100
  max_version: 90400
  tags: [ cluster, "extension:pg_stat_statements" ]
  metrics:
    - datname:      { usage: LABEL   ,description: Name of database }
    - query:        { usage: LABEL   ,description: MD5 hash of query text (no queryid before 9.4) }
    - calls:        { usage: COUNTER ,description: Number of times the statement was executed }
    - rows:         { usage: COUNTER ,description: Total number of rows retrieved or affected by the statement }
    - exec_time:    { usage: COUNTER ,scale: 1e-3 ,description: Total time spent executing the statement, in seconds }
    - io_time:      { usage: COUNTER ,scale: 1e-3 ,description: Total time the statement spent reading and writing blocks, in seconds (N/A before 9.4, always 0) }
    - sblk_hit:     { usage: COUNTER ,description: Total number of shared block cache hits by the statement }
    - sblk_read:    { usage: COUNTER ,description: Total number of shared blocks read by the statement }
    - sblk_dirtied: { usage: COUNTER ,description: Total number of shared blocks dirtied by the statement (N/A before 9.4, always 0) }
    - sblk_written: { usage: COUNTER ,description: Total number of shared blocks written by the statement }
