#==============================================================#
# 0720 pg_func
#==============================================================#
pg_func:
  desc: PostgreSQL function metrics
  query: SELECT CURRENT_CATALOG AS datname, schemaname || '.' || funcname AS funcname, sum(calls) AS calls, sum(total_time) AS total_time, sum(self_time) AS self_time FROM pg_stat_user_functions GROUP BY 2 ORDER BY 4 DESC LIMIT 128;
  ttl: 10
  min_version: 90100
  metrics:
    - datname:             { usage: LABEL    ,description: Name of belonged database }
    - funcname:            { usage: LABEL    ,description: Name of this function, may have multiple override }
    - calls:               { usage: COUNTER  ,description: Number of times this function has been called }
    - total_time:          { usage: COUNTER  ,scale: 1e-3 ,description: Total time spent in this function and all other functions called by it, in seconds }
    - self_time:           { usage: COUNTER  ,scale: 1e-3 ,description: Total time spent in this function itself, not including other functions called by it, in seconds }
