#==============================================================#
# 0830 pg_index_bloat
#==============================================================#
# pg_index_bloat require auxiliary view to work. Disable it or create auxiliary view before use:
pg_index_bloat:
  name: pg_index_bloat
  desc: PostgreSQL index bloat metrics, require auxiliary view pg_index_bloat to work
  query: SELECT datname, nspname || '.' || idxname AS idxname, size, ratio FROM pg_index_bloat ORDER BY size DESC LIMIT 64;
  ttl: 300
  timeout: 2
  min_version: 90400
  skip: true
  metrics:
    - datname:             { usage: LABEL    ,description: Database name of this index }
    - idxname:             { usage: LABEL    ,description: Schema qualified name of this index }
    - size:                { usage: GAUGE    ,description: Total bytes of this index }
    - ratio:               { usage: GAUGE    ,description: Estimated bloat ratio of this index from 0 to 1 }
